### PR TITLE
Feature history readjson

### PR DESCRIPTION
**Pull request by greatfighter**
Add readjson function in history page

### CODE REVIEW

**Review by KevinZxy1273 — APPROVED** [review]
Looks good, approved

**Review by marklhj-lee — APPROVED** [review]
We may have to change UI colours and how it reads data once it connects to backend.

**Review by greatfighter — COMMENTED** [review]
Ok

**Review by bingxiaan — APPROVED** [review]
looks good

**Review by ArthurQiangLi — APPROVED** [review]
Spencer fininsed reading and parsing json file for 'histor' page.

**Review by KevinZxy1273 — APPROVED** [review]
Looks good

**Pull request merged**
